package aacenc

/*
#include "external/aacenc/src/cmnMemory.h"
#include "external/aacenc/src/oper_32b.h"
#include "external/aacenc/src/aac_rom.h"
#include "external/aacenc/src/aacenc_core.h"
#include "external/aacenc/src/adj_thr.h"
#include "external/aacenc/src/band_nrg.h"
#include "external/aacenc/src/bit_cnt.h"
#include "external/aacenc/src/bitbuffer.h"
#include "external/aacenc/src/bitenc.h"
#include "external/aacenc/src/block_switch.h"
#include "external/aacenc/src/channel_map.h"
#include "external/aacenc/src/dyn_bits.h"
#include "external/aacenc/src/grp_data.h"
#include "external/aacenc/src/interface.h"
#include "external/aacenc/src/line_pe.h"
#include "external/aacenc/src/memalign.h"
#include "external/aacenc/src/ms_stereo.h"
#include "external/aacenc/src/pre_echo_control.h"
#include "external/aacenc/src/psy_configuration.h"
#include "external/aacenc/src/psy_main.h"
#include "external/aacenc/src/qc_main.h"
#include "external/aacenc/src/quantize.h"
#include "external/aacenc/src/sf_estim.h"
#include "external/aacenc/src/spreading.h"
#include "external/aacenc/src/stat_bits.h"
#include "external/aacenc/src/tns.h"
#include "external/aacenc/src/transform.h"
// #include "bridge.c"

#cgo CFLAGS: -std=gnu99 -Iexternal/aacenc/include -DUSE_DEFAULT_MEM
*/
import "C"
