load("@io_bazel_rules_go//go:def.bzl", "go_binary")

# Tested that it works, and it does, but requires the deps to be uncommented
# in the ../WORKSPACE file.
# go_binary(
#     name = "basic",
#     srcs = ["basic/basic.go"],
#     deps = [
#         "//:aac-go",
#         "@com_github_youpy_gowav//:go_default_library",
#     ],
# )
